name: NPM Cli

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: grunt release
        env:
          RELEASE_KEY: ${{secrets.RELEASE_KEY}}
