name: NPM Cli

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm install -g npm-cli-login
      - run: npm-cli-login -u marcegmail -p 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 -e marce.alba.m@gmail.com
      - run: cat ~/.npmrc
